//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebrootUI2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebrootUI2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsMenuItem {
            get {
                return ResourceManager.GetString("AccountsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire.
        /// </summary>
        public static string AcquireMenu {
            get {
                return ResourceManager.GetString("AcquireMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstrator.
        /// </summary>
        public static string Admin_MenuItem {
            get {
                return ResourceManager.GetString("Admin_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Audit_Back {
            get {
                return ResourceManager.GetString("Audit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Audit_From {
            get {
                return ResourceManager.GetString("Audit_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Audit_Level {
            get {
                return ResourceManager.GetString("Audit_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Audit_Message {
            get {
                return ResourceManager.GetString("Audit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Audit_Role {
            get {
                return ResourceManager.GetString("Audit_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Audit_To {
            get {
                return ResourceManager.GetString("Audit_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string AuditMenuItem {
            get {
                return ResourceManager.GetString("AuditMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargebook.
        /// </summary>
        public static string ChargebookMenuItem {
            get {
                return ResourceManager.GetString("ChargebookMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ConfigMenuItem {
            get {
                return ResourceManager.GetString("ConfigMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        public static string CreateInvoiceMenuItem {
            get {
                return ResourceManager.GetString("CreateInvoiceMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily summary.
        /// </summary>
        public static string DailySummaryMenuItem {
            get {
                return ResourceManager.GetString("DailySummaryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DepositMenuItem {
            get {
                return ResourceManager.GetString("DepositMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMenuItem {
            get {
                return ResourceManager.GetString("ErrorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string ExpiryMenuItem {
            get {
                return ResourceManager.GetString("ExpiryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Form_Company {
            get {
                return ResourceManager.GetString("Form_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Form_ConfirmPassword {
            get {
                return ResourceManager.GetString("Form_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Form_Name {
            get {
                return ResourceManager.GetString("Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Form_Password {
            get {
                return ResourceManager.GetString("Form_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Permission.
        /// </summary>
        public static string Form_Permissions {
            get {
                return ResourceManager.GetString("Form_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Form_Role {
            get {
                return ResourceManager.GetString("Form_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        public static string Form_SecurityQuestion {
            get {
                return ResourceManager.GetString("Form_SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        public static string Form_SecurutyAnswer {
            get {
                return ResourceManager.GetString("Form_SecurutyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryMenuItem {
            get {
                return ResourceManager.GetString("HistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Input_Name {
            get {
                return ResourceManager.GetString("Input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string InvoicesMenuItem {
            get {
                return ResourceManager.GetString("InvoicesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never mind.
        /// </summary>
        public static string Login_NeverMind {
            get {
                return ResourceManager.GetString("Login_NeverMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send me back to the sign-in screen.
        /// </summary>
        public static string Login_SendBackToLogin {
            get {
                return ResourceManager.GetString("Login_SendBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to admin.
        /// </summary>
        public static string Login_SignInToAdmin {
            get {
                return ResourceManager.GetString("Login_SignInToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master merchants.
        /// </summary>
        public static string MasterMerchantsMenuItem {
            get {
                return ResourceManager.GetString("MasterMerchantsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string MenuItem_Bin {
            get {
                return ResourceManager.GetString("MenuItem_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string MenuItem_M {
            get {
                return ResourceManager.GetString("MenuItem_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Merchant.
        /// </summary>
        public static string MenuItem_MM {
            get {
                return ResourceManager.GetString("MenuItem_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MenuItem_Module {
            get {
                return ResourceManager.GetString("MenuItem_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string MenuItem_T {
            get {
                return ResourceManager.GetString("MenuItem_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        public static string MenuItem_Van {
            get {
                return ResourceManager.GetString("MenuItem_Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        public static string MerchantsMenuItem {
            get {
                return ResourceManager.GetString("MerchantsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month summary.
        /// </summary>
        public static string MonthSummaryMenuItem {
            get {
                return ResourceManager.GetString("MonthSummaryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfileMenuItem {
            get {
                return ResourceManager.GetString("MyProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentMenuItem {
            get {
                return ResourceManager.GetString("PaymentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Permission_Other {
            get {
                return ResourceManager.GetString("Permission_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Permission_System {
            get {
                return ResourceManager.GetString("Permission_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Permission_Transaction {
            get {
                return ResourceManager.GetString("Permission_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string RefundMenuItem {
            get {
                return ResourceManager.GetString("RefundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsMenuItem {
            get {
                return ResourceManager.GetString("ReportsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role_MenuItem {
            get {
                return ResourceManager.GetString("Role_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutMenuItem {
            get {
                return ResourceManager.GetString("SignOutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemMenuItem {
            get {
                return ResourceManager.GetString("SystemMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string TransactionMenuItem {
            get {
                return ResourceManager.GetString("TransactionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string TransactionsViewMenuItem {
            get {
                return ResourceManager.GetString("TransactionsViewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string User_Answer {
            get {
                return ResourceManager.GetString("User_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password.
        /// </summary>
        public static string User_ChangePasswordTitle {
            get {
                return ResourceManager.GetString("User_ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string User_ConfirmPassword {
            get {
                return ResourceManager.GetString("User_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully reset your password. Please click.
        /// </summary>
        public static string User_ResetPWSuccessMessage1 {
            get {
                return ResourceManager.GetString("User_ResetPWSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string User_ResetPWSuccessMessage2 {
            get {
                return ResourceManager.GetString("User_ResetPWSuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to login..
        /// </summary>
        public static string User_ResetPWSuccessMessage3 {
            get {
                return ResourceManager.GetString("User_ResetPWSuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string User_ResetYourPassword {
            get {
                return ResourceManager.GetString("User_ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you a mail. Please go to the url there to complete reset..
        /// </summary>
        public static string User_SecurityQuestionSucceed {
            get {
                return ResourceManager.GetString("User_SecurityQuestionSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersMenuItem {
            get {
                return ResourceManager.GetString("UsersMenuItem", resourceCulture);
            }
        }
    }
}
